FROM node:lts-alpine3.16

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock to the container
COPY package.json yarn.lock ./

# Install dependencies with Yarn
RUN corepack prepare yarn@3.5.0 --activate \
    && yarn install --frozen-lockfile --non-interactive

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN yarn build

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["yarn", "start"]
