# https://github.com/belgattitude/nextjs-monorepo-example/blob/0dec79c0d8768361c0f13cf8e20398d149b0e5a9/.github/actions/yarn-nm-install/action.yml

name: "Monorepo install (yarn)"
description: "Run yarn install with node_modules linker and cache enabled"
inputs:
  enable-corepack:
    description: "Enable corepack"
    required: false
    default: "true"

  playwright-skip-browser-download:
    description: "Avoid playwright to download browsers automatically"
    required: false
    default: "1"

runs:
  using: "composite"

  steps:
    - name: ⚙️ Enable Corepack
      if: ${{ inputs.enable-corepack }} == 'true'
      shell: bash
      run: corepack enable

    - name: ⚙️ Expose yarn config as "$GITHUB_OUTPUT"
      id: yarn-config
      shell: bash
      run: |
        echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
    # Yarn rotates the downloaded cache archives, @see https://github.com/actions/setup-node/issues/325
    # Yarn cache is also reusable between arch and os.
    - name: ♻️ Restore yarn cache
      uses: actions/cache@v3
      id: yarn-download-cache
      with:
        path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
        key: yarn-download-cache-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-download-cache-
    # Save install_state (invalidated on yarn.lock changes)
    - name: ♻️ Restore yarn install state
      id: yarn-install-state-cache
      uses: actions/cache@v3
      with:
        path: .yarn/ci-cache/
        key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}

    - name: 📥 Install dependencies
      shell: bash
      run: |
        yarn install --immutable --inline-builds
      env:
        # CI optimizations. Overrides yarnrc.yml options (or their defaults) in the CI action.
        YARN_ENABLE_GLOBAL_CACHE: "false" # Use local cache folder to keep downloaded archives
        YARN_NM_MODE: "hardlinks-local" # Hardlinks-(local|global) reduces io / node_modules size
        YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state.gz # Very small speedup when lock does not change
        # Other environment variables
        HUSKY: "0" # By default do not run HUSKY install
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ inputs.playwright-skip-browser-download }}

    - name: Prisma generate schema and types
      shell: bash
      run: |
        yarn generate
        yarn dlx turbo build --filter database
