name: Docker Image Build CI

on:
  push:
    branches:
      - main

jobs:
  web:
    if: github.repository == 'sora-vp/baseline'
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "./apps/web/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sora-baseline-web:${{ github.ref_name }}
